### PR TITLE
Added Duo documentation

### PR DESCRIPTION
**Pull request by loptienj**

### CODE REVIEW

**Comment by jafrahm** [comment]
We do not have the Duo Enrollment worked out with ITSC yet, They need to be trained on how to perform the ID check and how to update RC.  Did we intend to post this on the website already?

**Comment by beckyyeager** [comment]
I'll take it down

Sent from my iPhone

On Dec 14, 2015, at 3:47 PM, jafrahm <notifications@github.com<mailto:notifications@github.com>> wrote:


We do not have the Duo Enrollment worked out with ITSC yet, They need to be trained on how to perform the ID check and how to update RC. Did we intend to post this on the website already?

-

**Comment by beckyyeager** [comment]
I have pulled this down for now

Sent from my iPhone

On Dec 14, 2015, at 3:47 PM, jafrahm <notifications@github.com<mailto:notifications@github.com>> wrote:


We do not have the Duo Enrollment worked out with ITSC yet, They need to be trained on how to perform the ID check and how to update RC. Did we intend to post this on the website already?

-

**Comment by loptienj** [comment]
Network diagram here: https://www.duosecurity.com/docs/duounix#network-diagram
With autopush enabled, the user never sees the "Select 1,2,3" prompt. The login hangs while waiting for Duo to respond and then continues. Duo "pushes" to phone app or calls registered number. Autopush is required for some apps to work correctly. The app shows an "Accept or Deny" option; the phone prompts user to press any button to allow.

Q: If a user has to change from Push to phone call, how do they do that?
A: With self-enroll off, an admin has to make this change. So contacting us would be required. With self-enroll on, any user logging in will get an enrollment prompt, which would bypass requirement for ID check.

Q: Do you need to auth again via Duo...
A: Yes. Every time you log in.

**Pull request merged**
